"use client";

import { AppContext } from "@/context";
import Header from "./Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppContext>
      <html lang="en">
        <body style={{ padding: "0 40px", position: "relative" }}>
          <Header />
          {children}
        </body>
      </html>
    </AppContext>
  );
}
