"use client";

import Header from "@/app/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ padding: "0 40px" }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
